export const SORT_CITY = "SORT_CITY";
export const GET_COUNTRY = "GET_COUNTRY";
export const GET_CITY = "GET_CITY";
export const PAGE_CITY = "PAGE_CITY";


export const GET_CITY_ERROR = "GET_CITY_ERROR";
export const GET_CITY_LOADING = "GET_CITY_LOADING";

export const DELETE_CITY_LOADING = "DELETE_CITY_LOADING";
export const DELETE_CITY_ERROR = "DELETE_CITY_ERROR"

export const COUNTRIES_LOADING = "COUNTRIES_LOADING";
export const COUNTRIES_ERROR = "COUNTRIES_ERROR";
